print("Marlon B. Velasco")
print("Mahinhin, Boac, Marinduque")
print("April 23, 2000")
print("Marinduque State College")
print("BSIT")
print("2nd Year")
print("B")
print("Reading books")
print("Playing Rubiks cube")
print("Eating")
print("Watching anime")
print("Playing online games")